Repository dotnet/fsharp, pull requests merged in 2018-06, with the labels that each got.

#5076 Provide fast generic comparer for bool values
  src/fsharp/FSharp.Core/prim-types.fs
Labels: Candidate for F# 4.5

#5031 [dev15.7] Fix annotation view regression
  vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs
Labels: Approved for v.Next

#5153 Remove value tuple 431 from VisualFSharpFull.vsix
  build/config/AssemblySignToolData.json
  packages.config
  vsintegration/Vsix/VisualFSharpFull/VisualFSharpFull.csproj
Labels: Approved for next preview

#5152 Update default fsharp.core to 4.5.0 and valuetuple to 4.4.0 for dotnet sdk apps
  fcs/FSharp.Compiler.Service.MSBuild.v12/FSharp.Compiler.Service.MSBuild.v12.fsproj
  fcs/FSharp.Compiler.Service.ProjectCracker/FSharp.Compiler.Service.ProjectCracker.fsproj
  fcs/FSharp.Compiler.Service.ProjectCrackerTool/FSharp.Compiler.Service.ProjectCrackerTool.fsproj
  fcs/FSharp.Compiler.Service.Tests/FSharp.Compiler.Service.Tests.fsproj
  fcs/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj
  fcs/samples/EditorService/EditorService.fsproj
  fcs/samples/FscExe/FscExe.fsproj
  fcs/samples/FsiExe/FsiExe.fsproj
  fcs/samples/InteractiveService/InteractiveService.fsproj
  fcs/samples/Tokenizer/Tokenizer.fsproj
  fcs/samples/UntypedTree/UntypedTree.fsproj
  src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.props
  tests/fsharp/core/samename/tempet.fsproj
  tests/service/data/samename/tempet.fsproj
Labels: Approved for next preview

#5107 Update templates to FSharp.Core 4.5.0
  build/config/AssemblySignToolData.json
  packages.config
  vsintegration/ProjectTemplates/ConsoleProject/Template/ConsoleApplication.fsproj
  vsintegration/ProjectTemplates/ConsoleProject/Template/ConsoleApplication.vstemplate
  vsintegration/ProjectTemplates/LibraryProject/Template/Library.fsproj
  vsintegration/ProjectTemplates/LibraryProject/Template/Library.vstemplate
  vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsproj
  vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.vstemplate
  vsintegration/Vsix/VisualFSharpFull/VisualFSharpFull.csproj
  vsintegration/Vsix/VisualFSharpTemplates/VisualFSharpTemplates.csproj
Labels: Approved for next preview

#5203 Move fix resolve mscorlib for dev15.8 preview 4
  src/fsharp/SimulatedMSBuildReferenceResolver.fs
  vsintegration/tests/UnitTests/VisualFSharp.UnitTests.fsproj
Labels: Approved for next preview

#5211 Clean up IntelliSense perf UI and flow options for IntelliSense
  vsintegration/src/FSharp.Editor/CodeFix/AddOpenCodeFixProvider.fs
  vsintegration/src/FSharp.Editor/CodeFix/ImplementInterfaceCodeFixProvider.fs
  vsintegration/src/FSharp.Editor/CodeFix/RenameUnusedValue.fs
  vsintegration/src/FSharp.Editor/Commands/HelpContextService.fs
  vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs
  vsintegration/src/FSharp.Editor/Diagnostics/SimplifyNameDiagnosticAnalyzer.fs
  vsintegration/src/FSharp.Editor/Diagnostics/UnusedDeclarationsAnalyzer.fs
  vsintegration/src/FSharp.Editor/Diagnostics/UnusedOpensDiagnosticAnalyzer.fs
  vsintegration/src/FSharp.Editor/DocumentHighlights/DocumentHighlightsService.fs
  vsintegration/src/FSharp.Editor/InlineRename/InlineRenameService.fs
  vsintegration/src/FSharp.Editor/LanguageService/FSharpCheckerExtensions.fs
  vsintegration/src/FSharp.Editor/LanguageService/SymbolHelpers.fs
  vsintegration/src/FSharp.Editor/Navigation/FindUsagesService.fs
  vsintegration/src/FSharp.Editor/Navigation/GoToDefinition.fs
  vsintegration/src/FSharp.Editor/Options/EditorOptions.fs
  vsintegration/src/FSharp.Editor/QuickInfo/QuickInfoProvider.fs
  vsintegration/src/FSharp.UIResources/FSharp.UIResources.csproj
  vsintegration/src/FSharp.UIResources/LanguageServicePerformanceOptionControl.xaml
  vsintegration/src/FSharp.UIResources/Strings.Designer.cs
  vsintegration/src/FSharp.UIResources/Strings.resx
  vsintegration/src/FSharp.UIResources/xlf/Strings.cs.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.de.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.en.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.es.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.fr.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.it.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.ja.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.ko.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.pl.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.pt-BR.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.ru.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.tr.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.zh-Hans.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.zh-Hant.xlf
Labels: Approved for next preview

#5146 Ref/Span fixes
  src/buildfromsource/FSharp.Compiler.Private/FSComp.fs
  src/buildfromsource/FSharp.Compiler.Private/FSComp.resx
  src/fsharp/CompileOps.fs
  src/fsharp/CompileOps.fsi
  src/fsharp/CompileOptions.fs
  src/fsharp/FSComp.txt
  src/fsharp/PostInferenceChecks.fs
  src/fsharp/PostInferenceChecks.fsi
  src/fsharp/TastOps.fs
  src/fsharp/TastOps.fsi
  src/fsharp/TypeChecker.fs
  src/fsharp/TypeChecker.fsi
  src/fsharp/xlf/FSComp.txt.cs.xlf
  src/fsharp/xlf/FSComp.txt.de.xlf
  src/fsharp/xlf/FSComp.txt.en.xlf
  src/fsharp/xlf/FSComp.txt.es.xlf
  src/fsharp/xlf/FSComp.txt.fr.xlf
  src/fsharp/xlf/FSComp.txt.it.xlf
  src/fsharp/xlf/FSComp.txt.ja.xlf
  src/fsharp/xlf/FSComp.txt.ko.xlf
  src/fsharp/xlf/FSComp.txt.pl.xlf
  src/fsharp/xlf/FSComp.txt.pt-BR.xlf
  src/fsharp/xlf/FSComp.txt.ru.xlf
  src/fsharp/xlf/FSComp.txt.tr.xlf
  src/fsharp/xlf/FSComp.txt.zh-Hans.xlf
  src/fsharp/xlf/FSComp.txt.zh-Hant.xlf
  tests/fsharp/core/span/test.bsl
  tests/fsharp/core/span/test.fsx
  tests/fsharp/core/span/test2.bsl
  tests/fsharp/core/span/test2.fsx
  tests/fsharp/single-test.fs
  tests/fsharp/tests.fs
  tests/fsharp/typecheck/sigs/neg63.bsl
  tests/fsharp/typecheck/sigs/neg_byref_7.bsl
Labels: Approved for next preview

#5175 Fix ParseAndCheckDocument
  vsintegration/src/FSharp.Editor/LanguageService/FSharpCheckerExtensions.fs
Labels: Approved for next preview

#5257 Deadlock in QuickInfo, again. Fixes #5254
  vsintegration/src/FSharp.Editor/QuickInfo/Navigation.fs
  vsintegration/src/FSharp.Editor/QuickInfo/QuickInfoProvider.fs
Labels: Approved for next preview

#5250 Fix 5233 - PrivateScope member access
  src/absil/il.fs
  src/absil/il.fsi
  src/absil/ilprint.fs
  src/absil/ilreflect.fs
  src/absil/ilwrite.fs
  src/fsharp/symbols/Symbols.fs
Labels: Approved for next preview

#5243 Update Nuget package versions. and compiler tools version
  src/FSharpSource.Settings.targets
  src/utils/CompilerLocationUtils.fs
Labels: Approved for next preview

#5251 Rename collapsable to collapsible
  vsintegration/src/FSharp.UIResources/Strings.resx
  vsintegration/src/FSharp.UIResources/xlf/Strings.cs.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.de.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.en.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.es.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.fr.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.it.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.ja.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.ko.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.pl.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.pt-BR.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.ru.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.tr.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.zh-Hans.xlf
  vsintegration/src/FSharp.UIResources/xlf/Strings.zh-Hant.xlf
Labels: Approved for next preview
