Repository dotnet/fsharp, pull requests merged in 2019-06, with the labels that each got.

#6830 Attributes lists
  src/fsharp/TypeChecker.fs
  src/fsharp/ast.fs
  src/fsharp/pars.fsy
  src/fsharp/service/ServiceAssemblyContent.fs
  src/fsharp/service/ServiceStructure.fs
  src/fsharp/service/ServiceUntypedParse.fs
  tests/service/ServiceUntypedParseTests.fs
Labels: Area-Compiler

#6867 Add missing case for underscore in 'for _ ='
  src/fsharp/pars.fsy
  tests/fsharp/core/forexpression/test.fsx
Labels: Candidate for F# 4.7

#6357 Add maxDegreeOfParallelism to Async.Parallel
  src/fsharp/FSharp.Core/FSCore.resx
  src/fsharp/FSharp.Core/async.fs
  src/fsharp/FSharp.Core/async.fsi
  src/fsharp/FSharp.Core/xlf/FSCore.cs.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.de.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.es.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.fr.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.it.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.ja.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.ko.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.pl.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.pt-BR.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.ru.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.tr.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.zh-Hans.xlf
  src/fsharp/FSharp.Core/xlf/FSCore.zh-Hant.xlf
  tests/FSharp.Core.UnitTests/FSharp.Core/Microsoft.FSharp.Control/AsyncModule.fs
Labels: Candidate for F# 4.7

#6891 Ensure that Language Version support flows to Parser
  fcs/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj
  src/fsharp/CompileOps.fs
  src/fsharp/CompileOps.fsi
  src/fsharp/CompileOptions.fs
  src/fsharp/FSComp.txt
  src/fsharp/FSharp.Build/Fsc.fs
  src/fsharp/FSharp.Compiler.Private/FSharp.Compiler.Private.fsproj
  src/fsharp/LanguageFeatures.fs
  src/fsharp/LanguageFeatures.fsi
  src/fsharp/UnicodeLexing.fs
  src/fsharp/UnicodeLexing.fsi
  src/fsharp/ast.fs
  src/fsharp/fsi/fsi.fs
  src/fsharp/lex.fsl
  src/fsharp/pars.fsy
  src/fsharp/service/ServiceLexing.fs
  src/fsharp/service/service.fs
  src/fsharp/xlf/FSComp.txt.cs.xlf
  src/fsharp/xlf/FSComp.txt.de.xlf
  src/fsharp/xlf/FSComp.txt.es.xlf
  src/fsharp/xlf/FSComp.txt.fr.xlf
  src/fsharp/xlf/FSComp.txt.it.xlf
  src/fsharp/xlf/FSComp.txt.ja.xlf
  src/fsharp/xlf/FSComp.txt.ko.xlf
  src/fsharp/xlf/FSComp.txt.pl.xlf
  src/fsharp/xlf/FSComp.txt.pt-BR.xlf
  src/fsharp/xlf/FSComp.txt.ru.xlf
  src/fsharp/xlf/FSComp.txt.tr.xlf
  src/fsharp/xlf/FSComp.txt.zh-Hans.xlf
  src/fsharp/xlf/FSComp.txt.zh-Hant.xlf
  src/utils/CompilerLocationUtils.fs
  src/utils/prim-lexing.fs
  src/utils/prim-lexing.fsi
  tests/FSharp.Compiler.UnitTests/HashIfExpression.fs
  tests/fsharp/FSharpSuite.Tests.fsproj
  tests/fsharp/HandleExpects.fs
  tests/fsharp/core/members/basics/test.fs
  tests/fsharp/core/members/self-identifier/version46/test.fs
  tests/fsharp/core/members/self-identifier/version47/test.fs
  tests/fsharp/single-test.fs
  tests/fsharp/test-framework.fs
  tests/fsharp/tests.fs
Labels: Candidate for F# 4.7

#6734 Roslyn Shim - Round 2
  RoslynPackageVersion.txt
  eng/Versions.props
  vsintegration/src/FSharp.Editor/BlockComment/CommentSelectionService.fs
  vsintegration/src/FSharp.Editor/CodeFix/RemoveUnusedOpens.fs
  vsintegration/src/FSharp.Editor/CodeFix/SimplifyName.fs
  vsintegration/src/FSharp.Editor/CodeLens/FSharpCodeLensService.fs
  vsintegration/src/FSharp.Editor/Common/ContentType.fs
  vsintegration/src/FSharp.Editor/Common/RoslynHelpers.fs
  vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs
  vsintegration/src/FSharp.Editor/Completion/CompletionService.fs
  vsintegration/src/FSharp.Editor/Completion/CompletionUtils.fs
  vsintegration/src/FSharp.Editor/Completion/FileSystemCompletion.fs
  vsintegration/src/FSharp.Editor/Completion/SignatureHelp.fs
  vsintegration/src/FSharp.Editor/Diagnostics/DocumentDiagnosticAnalyzer.fs
  vsintegration/src/FSharp.Editor/Diagnostics/ProjectDiagnosticAnalyzer.fs
  vsintegration/src/FSharp.Editor/Diagnostics/SimplifyNameDiagnosticAnalyzer.fs
  vsintegration/src/FSharp.Editor/Diagnostics/UnusedDeclarationsAnalyzer.fs
  vsintegration/src/FSharp.Editor/Diagnostics/UnusedOpensDiagnosticAnalyzer.fs
  vsintegration/src/FSharp.Editor/DocumentHighlights/DocumentHighlightsService.fs
  vsintegration/src/FSharp.Editor/FSharp.Editor.fsproj
  vsintegration/src/FSharp.Editor/InlineRename/InlineRenameService.fs
  vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs
  vsintegration/src/FSharp.Editor/Navigation/FindUsagesService.fs
  vsintegration/src/FSharp.Editor/Navigation/GoToDefinition.fs
  vsintegration/src/FSharp.Editor/Navigation/GoToDefinitionService.fs
  vsintegration/src/FSharp.Editor/Navigation/NavigableSymbolsService.fs
  vsintegration/src/FSharp.Editor/Navigation/NavigateToSearchService.fs
  vsintegration/src/FSharp.Editor/Navigation/NavigationBarItemService.fs
  vsintegration/src/FSharp.Editor/Structure/BlockStructureService.fs
  vsintegration/src/FSharp.LanguageService/FSharp.LanguageService.fsproj
  vsintegration/tests/GetTypesVS.UnitTests/GetTypesVS.UnitTests.fsproj
  vsintegration/tests/UnitTests/VisualFSharp.UnitTests.fsproj
Labels: Approved for next preview
