Repository dotnet/fsharp, pull requests merged in 2020-08, with the labels that each got.

#8754 Further enhancements to nameof
  src/fsharp/AttributeChecking.fs
  src/fsharp/FSComp.txt
  src/fsharp/FSharp.Core/prim-types.fs
  src/fsharp/FSharp.Core/prim-types.fsi
  src/fsharp/NameResolution.fs
  src/fsharp/NameResolution.fsi
  src/fsharp/TypeChecker.fs
  tests/fsharp/core/nameof/preview/test.fsx
  tests/fsharpqa/Source/Conformance/Expressions/DataExpressions/NameOf/E_NameOfAdditionExpr.fs
  tests/fsharpqa/Source/Conformance/Expressions/DataExpressions/NameOf/env.lst
Labels: Candidate for F# 5

#8907 [RFC FS-1001] String Interpolation
  src/fsharp/CheckFormatStrings.fs
  src/fsharp/CheckFormatStrings.fsi
  src/fsharp/CompileOps.fs
  src/fsharp/ErrorLogger.fs
  src/fsharp/FSComp.txt
  src/fsharp/FSStrings.resx
  src/fsharp/FSharp.Core/printf.fs
  src/fsharp/FSharp.Core/printf.fsi
  src/fsharp/LanguageFeatures.fs
  src/fsharp/LanguageFeatures.fsi
  src/fsharp/LexFilter.fs
  src/fsharp/MethodCalls.fs
  src/fsharp/ParseHelpers.fs
  src/fsharp/PostInferenceChecks.fs
  src/fsharp/SyntaxTree.fs
  src/fsharp/SyntaxTreeOps.fs
  src/fsharp/TcGlobals.fs
  src/fsharp/TypeChecker.fs
  src/fsharp/TypedTreeOps.fs
  src/fsharp/TypedTreeOps.fsi
  src/fsharp/fsi/fsi.fs
  src/fsharp/lex.fsl
  src/fsharp/lexhelp.fs
  src/fsharp/lexhelp.fsi
  src/fsharp/pars.fsy
  src/fsharp/pplex.fsl
  src/fsharp/service/FSharpCheckerResults.fs
  src/fsharp/service/ServiceLexing.fs
  src/fsharp/service/ServiceLexing.fsi
  src/fsharp/service/ServiceParseTreeWalk.fs
  src/fsharp/service/ServiceUntypedParse.fs
  tests/FSharp.Compiler.UnitTests/FSharp.Compiler.UnitTests.fsproj
  tests/FSharp.Compiler.UnitTests/HashIfExpression.fs
  tests/FSharp.Core.UnitTests/SurfaceArea.fs
  tests/FSharp.Test.Utilities/CompilerAssert.fs
  tests/fsharp/Compiler/Language/StringInterpolation.fs
  tests/fsharp/FSharpSuite.Tests.fsproj
  tests/fsharp/core/printf-interpolated/test.fsx
  tests/fsharp/core/printf/test.fsx
  tests/fsharp/tests.fs
  tests/service/Common.fs
  tests/service/EditorTests.fs
  tests/service/ProjectAnalysisTests.fs
  tests/service/TokenizerTests.fs
  tests/service/data/CSharp_Analysis/CSharp_Analysis.csproj
  vsintegration/src/FSharp.Editor/AutomaticCompletion/BraceCompletionSessionProvider.fs
  vsintegration/src/FSharp.Editor/Completion/CompletionUtils.fs
  vsintegration/tests/UnitTests/BraceMatchingServiceTests.fs
  vsintegration/tests/UnitTests/CompletionProviderTests.fs
  vsintegration/tests/UnitTests/GoToDefinitionServiceTests.fs
  vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.General.fs
  vsintegration/tests/UnitTests/ProjectDiagnosticAnalyzerTests.fs
  vsintegration/tests/UnitTests/UnusedOpensTests.fs
  vsintegration/tests/UnitTests/VisualFSharp.UnitTests.fsproj
Labels: Candidate for F# vNext

#9513 Open Type Declaration updates
  src/fsharp/CompileOps.fs
  src/fsharp/ConstraintSolver.fs
  src/fsharp/ErrorLogger.fs
  src/fsharp/FSComp.txt
  src/fsharp/InfoReader.fs
  src/fsharp/LanguageFeatures.fs
  src/fsharp/LanguageFeatures.fsi
  src/fsharp/MethodCalls.fs
  src/fsharp/MethodOverrides.fs
  src/fsharp/NameResolution.fs
  src/fsharp/NameResolution.fsi
  src/fsharp/PrettyNaming.fs
  src/fsharp/SyntaxTree.fs
  src/fsharp/TypeChecker.fs
  src/fsharp/TypeChecker.fsi
  src/fsharp/TypedTree.fs
  src/fsharp/TypedTreeOps.fs
  src/fsharp/TypedTreeOps.fsi
  src/fsharp/pars.fsy
  src/fsharp/service/FSharpCheckerResults.fs
  src/fsharp/service/SemanticClassification.fs
  src/fsharp/service/ServiceParseTreeWalk.fs
  src/fsharp/service/ServiceUntypedParse.fs
  src/fsharp/service/ServiceUntypedParse.fsi
  src/fsharp/symbols/Symbols.fs
  src/fsharp/symbols/Symbols.fsi
  src/fsharp/xlf/FSComp.txt.cs.xlf
  src/fsharp/xlf/FSComp.txt.de.xlf
  src/fsharp/xlf/FSComp.txt.es.xlf
  src/fsharp/xlf/FSComp.txt.fr.xlf
  src/fsharp/xlf/FSComp.txt.it.xlf
  src/fsharp/xlf/FSComp.txt.ja.xlf
  src/fsharp/xlf/FSComp.txt.ko.xlf
  src/fsharp/xlf/FSComp.txt.pl.xlf
  src/fsharp/xlf/FSComp.txt.pt-BR.xlf
  src/fsharp/xlf/FSComp.txt.ru.xlf
  src/fsharp/xlf/FSComp.txt.tr.xlf
  src/fsharp/xlf/FSComp.txt.zh-Hans.xlf
  src/fsharp/xlf/FSComp.txt.zh-Hant.xlf
  tests/FSharp.Test.Utilities/Compiler.fs
  tests/FSharp.Test.Utilities/CompilerAssert.fs
  tests/fsharp/Compiler/Language/DefaultInterfaceMemberTests.fs
  tests/fsharp/Compiler/Language/OpenStaticClasses.fs
  tests/fsharp/Compiler/Language/OpenTypeDeclarationTests.fs
  tests/fsharp/FSharpSuite.Tests.fsproj
  tests/fsharp/typecheck/sigs/neg95.bsl
  tests/service/InteractiveCheckerTests.fs
  tests/service/ProjectAnalysisTests.fs
  tests/service/StructureTests.fs
  vsintegration/tests/UnitTests/CompletionProviderTests.fs
  vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.Completion.fs
Labels: Candidate for F# 5

#9999 IL Verifiication in the new testing framework
  eng/Versions.props
  eng/build.sh
  tests/FSharp.Compiler.ComponentTests/EmittedIL/Literals.fs
  tests/FSharp.Compiler.ComponentTests/EmittedIL/TailCalls.fs
  tests/FSharp.Compiler.ComponentTests/FSharp.Compiler.ComponentTests.fsproj
  tests/FSharp.Test.Utilities/Compiler.fs
  tests/FSharp.Test.Utilities/ILChecker.fs
  tests/FSharp.Test.Utilities/TestFramework.fs
  tests/fsharp/Compiler/CodeGen/EmittedIL/LiteralValue.fs
  tests/fsharp/FSharpSuite.Tests.fsproj
Labels: Area-Infrastructure, Test
