Repository dotnet/fsharp, pull requests merged in 2020-01, with the labels that each got.

#7839 [FS-1080] Add new syntax option for Float32.
  src/fsharp/LanguageFeatures.fs
  src/fsharp/LanguageFeatures.fsi
  src/fsharp/lex.fsl
  tests/FSharp.Core.UnitTests/FSharp.Core.UnitTests.fsproj
  tests/fsharp/Compiler/CompilerAssert.fs
  tests/fsharp/Compiler/Conformance/BasicGrammarElements/BasicConstants.fs
  tests/fsharpqa/Source/Conformance/BasicGrammarElements/Constants/E_UnderscoreLiterals.fs
Labels: Candidate for F# vNext

#8277 Include System.Buffers in vsix
  src/fsharp/FSharp.Compiler.Private/FSharp.Compiler.Private.fsproj
  src/fsharp/FSharp.Compiler.Private/FSharp.Compiler.Private.netcore.nuspec
  src/fsharp/FSharp.Compiler.nuget/Microsoft.FSharp.Compiler.nuspec
  vsintegration/Directory.Build.targets
Labels: Urgency-Now

#7756 [RFC FS-1063] Applicative CEs via and! and BindReturn
  src/fsharp/CompileOps.fs
  src/fsharp/FSComp.txt
  src/fsharp/FSStrings.resx
  src/fsharp/LanguageFeatures.fs
  src/fsharp/LanguageFeatures.fsi
  src/fsharp/LexFilter.fs
  src/fsharp/TypeChecker.fs
  src/fsharp/ast.fs
  src/fsharp/lex.fsl
  src/fsharp/pars.fsy
  src/fsharp/service/ServiceAssemblyContent.fs
  src/fsharp/service/ServiceInterfaceStubGenerator.fs
  src/fsharp/service/ServiceLexing.fs
  src/fsharp/service/ServiceParseTreeWalk.fs
  src/fsharp/service/ServiceStructure.fs
  src/fsharp/service/ServiceUntypedParse.fs
  src/fsharp/xlf/FSComp.txt.cs.xlf
  src/fsharp/xlf/FSComp.txt.de.xlf
  src/fsharp/xlf/FSComp.txt.es.xlf
  src/fsharp/xlf/FSComp.txt.fr.xlf
  src/fsharp/xlf/FSComp.txt.it.xlf
  src/fsharp/xlf/FSComp.txt.ja.xlf
  src/fsharp/xlf/FSComp.txt.ko.xlf
  src/fsharp/xlf/FSComp.txt.pl.xlf
  src/fsharp/xlf/FSComp.txt.pt-BR.xlf
  src/fsharp/xlf/FSComp.txt.ru.xlf
  src/fsharp/xlf/FSComp.txt.tr.xlf
  src/fsharp/xlf/FSComp.txt.zh-Hans.xlf
  src/fsharp/xlf/FSComp.txt.zh-Hant.xlf
  src/fsharp/xlf/FSStrings.cs.xlf
  src/fsharp/xlf/FSStrings.de.xlf
  src/fsharp/xlf/FSStrings.es.xlf
  src/fsharp/xlf/FSStrings.fr.xlf
  src/fsharp/xlf/FSStrings.it.xlf
  src/fsharp/xlf/FSStrings.ja.xlf
  src/fsharp/xlf/FSStrings.ko.xlf
  src/fsharp/xlf/FSStrings.pl.xlf
  src/fsharp/xlf/FSStrings.pt-BR.xlf
  src/fsharp/xlf/FSStrings.ru.xlf
  src/fsharp/xlf/FSStrings.tr.xlf
  src/fsharp/xlf/FSStrings.zh-Hans.xlf
  src/fsharp/xlf/FSStrings.zh-Hant.xlf
  tests/fsharp/Compiler/CompilerAssert.fs
  tests/fsharp/Compiler/Conformance/DataExpressions/ComputationExpressions.fs
  tests/fsharp/FSharpSuite.Tests.fsproj
  tests/fsharp/perf/computation-expressions/dependency_graph.fsx
  tests/fsharpqa/Source/CodeGen/EmittedIL/.il.bsl
  tests/fsharpqa/Source/CodeGen/EmittedIL/ComputationExpressions/ComputationExprLibrary.fs
  vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.Completion.fs
  vsintegration/tests/UnitTests/TestLib.LanguageService.fs
  vsintegration/tests/UnitTests/TestLib.Salsa.fs
Labels: Candidate for F# 5, Candidate for F# vNext
