Repository dotnet/fsharp, pull requests merged in 2024-05, with the labels that each got.

#17104 Re-enable realsig
  Directory.Build.props
  src/Compiler/Checking/AugmentWithHashCompare.fs
  tests/FSharp.Compiler.ComponentTests/EmittedIL/CCtorDUWithMember/CCtorDUWithMember.fs
  tests/FSharp.Compiler.Service.Tests/FSharp.Compiler.Service.SurfaceArea.netstandard20.debug.bsl
  tests/FSharp.Compiler.Service.Tests/FSharp.Compiler.Service.SurfaceArea.netstandard20.release.bsl
  tests/FSharp.Compiler.Service.Tests/SurfaceArea.fs
Labels: NO_RELEASE_NOTES

#16860 Sourcebuild perf perhaps
  Build.cmd
  Directory.Build.props
  Directory.Build.targets
  FSharpBuild.Directory.Build.targets
  Microsoft.FSharp.Compiler.sln
  Proto.sln
  azure-pipelines-PR.yml
  build.sh
  buildtools/AssemblyCheck/AssemblyCheck.fsproj
  buildtools/buildtools.proj
  buildtools/fslex/fslex.fsproj
  buildtools/fsyacc/fsyacc.fsproj
  eng/Build.ps1
  eng/SourceBuildPrebuiltBaseline.xml
  eng/build-utils.ps1
  eng/build.sh
  eng/targets/NGenBinaries.targets
  eng/test-determinism.ps1
  proto.proj
  src/Compiler/FSharp.Compiler.Service.fsproj
  src/Directory.Build.targets
  src/FSharp.Build/FSharp.Build.fsproj
  src/FSharp.Build/Fsc.fs
  src/FSharp.Build/Microsoft.FSharp.Targets
  src/FSharp.Compiler.Interactive.Settings/FSharp.Compiler.Interactive.Settings.fsproj
  src/FSharp.Core/FSharp.Core.fsproj
  src/FSharp.DependencyManager.Nuget/FSharp.DependencyManager.Nuget.fsproj
  src/Microsoft.FSharp.Compiler/Microsoft.FSharp.Compiler.fsproj
  src/Microsoft.FSharp.Compiler/Microsoft.FSharp.Compiler.nuspec
  src/fsc/fsc.targets
  src/fsc/fscAnyCpuProject/fscAnyCpu.fsproj
  src/fsc/fscArm64Project/fscArm64.fsproj
  src/fsc/fscProject/fsc.fsproj
  src/fsi/fsi.targets
  src/fsi/fsiAnyCpuProject/fsiAnyCpu.fsproj
  src/fsi/fsiArm64Project/fsiArm64.fsproj
  src/fsi/fsiProject/fsi.fsproj
  tests/Directory.Build.props
  tests/fsharpqa/run.fsharpqa.test.fsx
  tests/fsharpqa/testenv/src/HostedCompilerServer/HostedCompilerServer.fsproj
  vsintegration/Templates.Directory.Build.props
  vsintegration/tests/UnitTests/Tests.Build.fs
Labels: NO_RELEASE_NOTES

#17144 Update VS2017.11 dependencies
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs
  vsintegration/tests/Salsa/VisualFSharp.Salsa.fsproj
Labels: NO_RELEASE_NOTES

#17176 Cherry pick
  eng/Versions.props
  global.json
  src/Compiler/Optimize/Optimizer.fs
  tests/FSharp.Compiler.ComponentTests/EmittedIL/Inlining/Inlining.fs
Labels: NO_RELEASE_NOTES

#17168 FS1118 on inlined function in private module from SDK 8.0.300 #17161
  src/Compiler/Optimize/Optimizer.fs
  tests/AheadOfTime/Trimming/check.ps1
  tests/FSharp.Compiler.ComponentTests/EmittedIL/Inlining/Inlining.fs
Labels: NO_RELEASE_NOTES

#17151 Fix primary assembly heuristic + clean up duplicate code
  src/Compiler/AbstractIL/il.fs
  src/Compiler/AbstractIL/ilread.fs
Labels: NO_RELEASE_NOTES

#17173 Enforce `AttributeTargets.Interface`
  docs/release-notes/.FSharp.Compiler.Service/8.0.400.md
  docs/release-notes/.FSharp.Core/8.0.400.md
  src/Compiler/Checking/CheckDeclarations.fs
  src/FSharp.Core/prim-types.fs
  src/FSharp.Core/prim-types.fsi
  tests/FSharp.Compiler.ComponentTests/Conformance/BasicGrammarElements/CustomAttributes/AttributeUsage/AttributeTargetsIsInterface.fs
  tests/FSharp.Compiler.ComponentTests/Conformance/BasicGrammarElements/CustomAttributes/AttributeUsage/AttributeUsage.fs
  tests/FSharp.Compiler.ComponentTests/Conformance/BasicGrammarElements/CustomAttributes/AttributeUsage/E_AttributeTargetIsClass01.fs
  tests/FSharp.Compiler.ComponentTests/Conformance/BasicGrammarElements/CustomAttributes/AttributeUsage/E_AttributeTargetIsInterface.fs
  vsintegration/src/FSharp.ProjectSystem.FSharp/Project.fs
Labels: NO_RELEASE_NOTES

#17189 Fix inlining regression: https://github.com/dotnet/fsharp/issues/17161
  eng/Versions.props
  global.json
  src/Compiler/Optimize/Optimizer.fs
  tests/FSharp.Compiler.ComponentTests/EmittedIL/Inlining/Inlining.fs
Labels: NO_RELEASE_NOTES, Servicing-consider

#17201 Fix inlining regression
  eng/Versions.props
  global.json
  src/Compiler/Optimize/Optimizer.fs
  tests/FSharp.Compiler.ComponentTests/EmittedIL/Inlining/Inlining.fs
Labels: NO_RELEASE_NOTES, Servicing-approved

#17208 Fix MultipleDiagnosticsLoggers.Parallel deadlock
  src/Compiler/Facilities/DiagnosticsLogger.fs
  tests/FSharp.Compiler.UnitTests/BuildGraphTests.fs
Labels: NO_RELEASE_NOTES

#17270 Fix plain build of FSC fsproj
  buildtools/fslex/fslex.fsproj
  buildtools/fsyacc/fsyacc.fsproj
  src/Compiler/FSharp.Compiler.Service.fsproj
Labels: NO_RELEASE_NOTES
